import { ArrowUpRight, Circle } from 'lucide-react';
import { ArrowLink, PageIntro, SectionLabel } from '@/components/site-shell';

const team = [{ initials: 'EL', name: 'Elena Lowe', role: 'Founder · People strategy' }, { initials: 'JM', name: 'Jonas Moore', role: 'Partner · Talent & growth' }, { initials: 'RK', name: 'Rina Kaur', role: 'Lead · Operations design' }];
export default function About() {
  return <div><PageIntro eyebrow="About Harbor People" title="The human side of the plan.">We are a small, senior team helping founders turn good intentions into ways of working that hold up under pressure.</PageIntro>
    <section className="border-y border-border bg-[#dce9e5]"><div className="mx-auto grid max-w-[1320px] gap-12 px-5 py-20 sm:px-8 lg:grid-cols-[.7fr_1.3fr] lg:px-12 lg:py-32"><div><SectionLabel>Our point of view</SectionLabel></div><div><p className="font-display text-4xl leading-[1.04] tracking-[-.03em] text-primary sm:text-6xl">The best people work is quietly structural.</p><p className="mt-8 max-w-xl text-lg leading-8 text-primary/65">It lives in the questions asked at interview, the first-week experience, the clarity of a manager’s expectations and the trust built in the small moments. We work there.</p></div></div></section>
    <section className="mx-auto max-w-[1320px] px-5 py-24 sm:px-8 lg:px-12 lg:py-36"><div className="grid gap-14 lg:grid-cols-[1fr_1fr]"><div><SectionLabel>Started in 2018</SectionLabel><h2 className="mt-5 max-w-xl font-display text-5xl leading-[.98] tracking-[-.04em] text-primary sm:text-7xl">Enough distance to see clearly. Enough care to stay close.</h2></div><div className="space-y-8 text-base leading-8 text-muted-foreground"><p>Harbor began with a simple observation: ambitious businesses were often making deeply human decisions with tools designed for spreadsheets.</p><p>Since then, we have partnered with 68 teams across technology, climate, design and culture. Sometimes we are in the room for a week. Sometimes for two years. The measure is the same: does the team feel more capable when we leave?</p><div className="grid grid-cols-2 gap-5 border-t border-border pt-8"><div><p className="font-display text-5xl text-primary">68</p><p className="mt-2 text-xs uppercase tracking-widest">teams supported</p></div><div><p className="font-display text-5xl text-primary">9/10</p><p className="mt-2 text-xs uppercase tracking-widest">would recommend</p></div></div></div></div></section>
    <section className="bg-primary text-primary-foreground"><div className="mx-auto max-w-[1320px] px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><SectionLabel>Small team, broad lens</SectionLabel><div className="mt-12 grid gap-4 md:grid-cols-3">{team.map((person) => <div key={person.name} data-testid={`card-team-${person.initials}`} className="border-t border-primary-foreground/20 py-6"><div className="grid h-16 w-16 place-items-center rounded-full bg-[#e8b39b] font-semibold text-primary">{person.initials}</div><h3 className="mt-8 font-display text-3xl">{person.name}</h3><p className="mt-2 text-sm text-primary-foreground/55">{person.role}</p></div>)}</div></div></section>
    <section className="mx-auto flex max-w-[1320px] flex-col gap-8 px-5 py-24 sm:px-8 lg:flex-row lg:items-end lg:justify-between lg:px-12 lg:py-32"><div><SectionLabel>Our promise</SectionLabel><p className="mt-5 max-w-2xl font-display text-4xl leading-tight text-primary sm:text-5xl">No drama. No jargon. Just better conditions for people to do meaningful work.</p></div><ArrowLink href="/contact">Meet us where you are <ArrowUpRight className="hidden" /></ArrowLink></section>
  </div>;
}