import { ArrowDown, ArrowUpRight, Check, Quote } from 'lucide-react';
import { Link } from 'wouter';
import { ArrowLink, SectionLabel } from '@/components/site-shell';
import { ThreeHero } from '@/components/three-hero';

const services = [
  { n: '01', title: 'Hire the right shape', copy: 'Search, selection and onboarding for the roles that change a company’s trajectory.' },
  { n: '02', title: 'Make work work', copy: 'People operations, payroll and policies that remove friction before it finds your team.' },
  { n: '03', title: 'Grow with intent', copy: 'Workplace strategy for leaders building something worth staying for.' },
];

export default function Home() {
  return <div>
    <section className="relative isolate min-h-[710px] overflow-hidden bg-[#dce9e5]"><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_35%,rgba(255,242,204,.8),transparent_28%),linear-gradient(120deg,#dce9e5_20%,#c7dcda_100%)]" /><ThreeHero /><div className="relative z-10 mx-auto flex min-h-[710px] max-w-[1320px] flex-col justify-between px-5 pb-9 pt-20 sm:px-8 lg:px-12 lg:pt-28"><div className="max-w-3xl"><p className="eyebrow reveal text-primary/60">An HR partner for the in-between</p><h1 data-testid="heading-home-hero" className="reveal delay-1 mt-7 max-w-3xl font-display text-[4.25rem] leading-[.88] tracking-[-.055em] text-primary sm:text-8xl lg:text-[9rem]">Make room<br /><span className="text-accent">for good</span> work.</h1><p className="reveal delay-2 mt-8 max-w-md text-base leading-6 text-primary/70 sm:text-lg">Harbor People helps growing teams build the conditions where ambitious, thoughtful people do their best work.</p></div><div className="reveal delay-3 flex items-end justify-between"><Link href="/contact" data-testid="link-hero-cta" className="group inline-flex items-center gap-3 rounded-full bg-primary px-6 py-4 text-sm font-semibold text-primary-foreground transition-transform hover:-translate-y-1">Tell us where it hurts <ArrowUpRight className="h-4 w-4 transition-transform group-hover:translate-x-1 group-hover:-translate-y-1" /></Link><div className="hidden items-center gap-2 text-xs font-semibold text-primary/60 sm:flex"><ArrowDown className="h-4 w-4 animate-bounce" /> Scroll to explore</div></div></div></section>
    <section className="mx-auto grid max-w-[1320px] gap-12 px-5 py-24 sm:px-8 lg:grid-cols-[.8fr_1.2fr] lg:px-12 lg:py-36"><div><SectionLabel>The useful bit</SectionLabel></div><div><h2 data-testid="heading-home-manifesto" className="max-w-3xl font-display text-4xl leading-[1.05] tracking-[-.035em] text-primary sm:text-6xl">People problems rarely arrive as people problems.</h2><p className="mt-8 max-w-xl text-lg leading-8 text-muted-foreground">A missed hire looks like a revenue problem. A clunky policy looks like a culture problem. We look underneath the noise, then make the next right thing easier.</p><ArrowLink href="/about" >How we think</ArrowLink></div></section>
    <section className="bg-primary text-primary-foreground"><div className="mx-auto max-w-[1320px] px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="flex flex-col justify-between gap-8 border-b border-primary-foreground/20 pb-8 sm:flex-row sm:items-end"><div><SectionLabel>Where we help</SectionLabel><h2 className="mt-4 font-display text-4xl tracking-[-.03em] sm:text-6xl">The whole people picture.</h2></div><p className="max-w-xs text-sm leading-6 text-primary-foreground/60">Practical support, senior thinking, no theatre.</p></div><div className="divide-y divide-primary-foreground/15">{services.map((service) => <div key={service.n} data-testid={`card-service-${service.n}`} className="group grid gap-4 py-8 transition-colors hover:text-accent sm:grid-cols-[100px_1fr_1fr] sm:gap-8"><span className="font-mono text-xs text-primary-foreground/45">{service.n}</span><h3 className="font-display text-3xl sm:text-4xl">{service.title}</h3><p className="max-w-sm text-sm leading-6 text-primary-foreground/60 group-hover:text-primary-foreground/75">{service.copy}</p></div>)}</div><div className="mt-10"><ArrowLink href="/services" light>See all services</ArrowLink></div></div></section>
    <section className="mx-auto max-w-[1320px] px-5 py-24 sm:px-8 lg:px-12 lg:py-36"><div className="grid gap-10 lg:grid-cols-[1.15fr_.85fr]"><div className="overflow-hidden rounded-[2rem] bg-[#e8b39b] p-8 sm:p-14"><div className="flex items-start justify-between"><SectionLabel>Field note / 004</SectionLabel><span className="text-sm text-primary/50">2024</span></div><h2 className="mt-28 max-w-lg font-display text-5xl leading-[.95] tracking-[-.045em] text-primary sm:text-7xl">From 12 to 48, without losing the plot.</h2><p className="mt-8 max-w-sm text-sm leading-6 text-primary/70">How a climate-tech team built a clear operating rhythm before their next round.</p><ArrowLink href="/work" >Read the case study</ArrowLink></div><div className="flex flex-col justify-end rounded-[2rem] border border-border bg-card p-8 sm:p-12"><Quote className="h-9 w-9 text-accent" fill="currentColor" /><blockquote className="mt-8 font-display text-3xl leading-tight tracking-[-.02em] text-primary">“They gave us the confidence to stop improvising.”</blockquote><div className="mt-10 flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-full bg-secondary text-xs font-bold text-primary">AM</div><div><p className="text-sm font-semibold">Ari Mendez</p><p className="text-xs text-muted-foreground">Co-founder, Loam Systems</p></div></div></div></div></section>
    <section className="bg-[#f1d7b6]"><div className="mx-auto flex max-w-[1320px] flex-col justify-between gap-10 px-5 py-20 sm:px-8 lg:flex-row lg:items-end lg:px-12 lg:py-28"><div><SectionLabel>Not another vendor</SectionLabel><h2 className="mt-5 max-w-2xl font-display text-5xl leading-[.98] tracking-[-.04em] text-primary sm:text-7xl">A calmer way to build a company.</h2></div><div className="max-w-sm"><div className="space-y-4 text-sm text-primary/75"><p><Check className="mr-2 inline h-4 w-4 text-accent" />Senior people on every project</p><p><Check className="mr-2 inline h-4 w-4 text-accent" />Straight answers, plain language</p><p><Check className="mr-2 inline h-4 w-4 text-accent" />Built around your actual context</p></div><Link href="/contact" data-testid="link-home-final-cta" className="mt-10 inline-flex items-center gap-2 rounded-full bg-primary px-6 py-4 text-sm font-semibold text-primary-foreground transition-transform hover:-translate-y-1">Let’s talk <ArrowUpRight className="h-4 w-4" /></Link></div></div></section>
  </div>;
}