import { ArrowUpRight, BriefcaseBusiness, Compass, Handshake, Layers3, ShieldCheck, Sparkles } from 'lucide-react';
import { ArrowLink, PageIntro, SectionLabel } from '@/components/site-shell';

const offerings = [{ icon: BriefcaseBusiness, title: 'Hiring & talent', text: 'From the first role profile to the final yes. A search process that respects the candidate and protects your time.', list: ['Role architecture', 'Search & selection', 'Interview design', 'Onboarding that lands'] }, { icon: ShieldCheck, title: 'People operations', text: 'The essential infrastructure of a healthy team, made legible and useful for everyone.', list: ['Contracts & payroll', 'Policies & handbooks', 'Performance rhythms', 'Manager support'] }, { icon: Compass, title: 'Workplace strategy', text: 'A clear-eyed look at how your team works today, and what it needs next.', list: ['Ways of working', 'Org design', 'Culture diagnostics', 'Leadership advising'] }];
const iconSet = [Handshake, Layers3, Sparkles];
export default function Services() {
  return <div><PageIntro eyebrow="What we do" title="The work behind the work.">A flexible bench of senior people partners, operators and talent specialists for the moments that matter.</PageIntro>
    <section className="bg-primary text-primary-foreground"><div className="mx-auto max-w-[1320px] px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="mb-14 max-w-2xl"><SectionLabel>Our offer</SectionLabel><h2 className="mt-5 font-display text-4xl leading-tight sm:text-6xl">Useful in the room. Useful after we leave.</h2></div><div className="grid gap-px overflow-hidden rounded-2xl border border-primary-foreground/15 bg-primary-foreground/15 md:grid-cols-3">{offerings.map((item, index) => { const Icon = item.icon; return <article key={item.title} data-testid={`card-offering-${index}`} className="bg-primary p-7 sm:p-9"><Icon className="h-7 w-7 text-accent" /><h3 className="mt-16 font-display text-3xl">{item.title}</h3><p className="mt-4 text-sm leading-6 text-primary-foreground/60">{item.text}</p><ul className="mt-8 space-y-3 border-t border-primary-foreground/15 pt-6">{item.list.map((line) => <li key={line} className="flex items-center gap-2 text-sm text-primary-foreground/80"><span className="h-1.5 w-1.5 rounded-full bg-accent" />{line}</li>)}</ul></article>; })}</div></div></section>
    <section className="mx-auto max-w-[1320px] px-5 py-24 sm:px-8 lg:px-12 lg:py-36"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><SectionLabel>How it works</SectionLabel><p className="mt-6 max-w-xs text-sm leading-6 text-muted-foreground">The shape changes. The approach stays thoughtful.</p></div><div className="space-y-0">{['Listen first', 'Make the invisible visible', 'Build the next useful thing', 'Leave the team stronger'].map((step, index) => { const Icon = iconSet[index % iconSet.length]; return <div key={step} className="flex items-center gap-5 border-b border-border py-7"><span className="font-mono text-xs text-accent">0{index + 1}</span><Icon className="h-5 w-5 text-primary" /><h3 className="font-display text-3xl text-primary">{step}</h3></div>; })}</div></div></section>
    <section className="mx-5 mb-24 overflow-hidden rounded-[2rem] bg-[#e8b39b] sm:mx-8 lg:mx-12"><div className="mx-auto flex max-w-[1320px] flex-col justify-between gap-10 px-6 py-14 sm:px-12 lg:flex-row lg:items-center lg:py-20"><div><p className="eyebrow text-primary/50">Have a knot to untangle?</p><h2 className="mt-5 max-w-xl font-display text-4xl leading-tight text-primary sm:text-6xl">Bring the messy version.</h2></div><ArrowLink href="/contact">Start a conversation <ArrowUpRight className="hidden" /></ArrowLink></div></section>
  </div>;
}