import { ArrowUpRight, Quote } from 'lucide-react';
import { ArrowLink, PageIntro, SectionLabel } from '@/components/site-shell';

const cases = [{ tag: 'CLIMATE · PEOPLE OPS', title: 'A team that could scale without hardening.', detail: 'Loam Systems needed the operating system for their next chapter. We built a practical people foundation across 18 weeks.', result: 'From 12 → 48 people with a clear rhythm.' }, { tag: 'DESIGN · TALENT', title: 'Hiring as a signal of what comes next.', detail: 'For Northline Studio, every hire had to strengthen their point of view. We reshaped the search around that ambition.', result: '7 critical hires. 94% offer acceptance.' }, { tag: 'FINANCE · LEADERSHIP', title: 'More trust, fewer heroic managers.', detail: 'A leadership reset for a fast-moving fintech, translating values into decisions managers could actually make.', result: 'Manager confidence up 31 points.' }];
export default function Work() {
  return <div><PageIntro eyebrow="Selected work" title="Proof, not performance.">We measure our work by what becomes easier, clearer and more possible for the people inside the business.</PageIntro>
    <section className="mx-auto max-w-[1320px] px-5 pb-24 sm:px-8 lg:px-12 lg:pb-36"><div className="space-y-5">{cases.map((item, index) => <article key={item.tag} data-testid={`card-case-${index}`} className={`group grid gap-8 rounded-[1.6rem] p-7 sm:p-12 lg:grid-cols-[.75fr_1.25fr] ${index === 0 ? 'bg-[#dce9e5]' : index === 1 ? 'bg-[#f1d7b6]' : 'bg-primary text-primary-foreground'}`}><div className="flex flex-col justify-between"><p className={`eyebrow ${index === 2 ? 'text-accent' : 'text-primary/50'}`}>{item.tag}</p><div className="mt-16 hidden text-sm lg:block"><span className="inline-flex h-12 w-12 items-center justify-center rounded-full border border-current transition-transform group-hover:rotate-45"><ArrowUpRight className="h-4 w-4" /></span></div></div><div><h2 className="max-w-2xl font-display text-4xl leading-[1.03] tracking-[-.03em] sm:text-6xl">{item.title}</h2><p className={`mt-7 max-w-lg leading-7 ${index === 2 ? 'text-primary-foreground/65' : 'text-primary/65'}`}>{item.detail}</p><p className={`mt-10 border-t pt-5 text-sm font-semibold ${index === 2 ? 'border-primary-foreground/20' : 'border-primary/20'}`}>{item.result}</p></div></article>)}</div></section>
    <section className="border-y border-border bg-[#dce9e5]"><div className="mx-auto grid max-w-[1320px] gap-12 px-5 py-20 sm:px-8 lg:grid-cols-[.7fr_1.3fr] lg:px-12 lg:py-28"><div><SectionLabel>In their words</SectionLabel></div><div><Quote className="h-8 w-8 text-accent" fill="currentColor" /><blockquote data-testid="quote-featured" className="mt-7 max-w-3xl font-display text-4xl leading-[1.05] tracking-[-.03em] text-primary sm:text-6xl">“Harbor gave us a language for the company we were becoming — and the tools to make it real.”</blockquote><div className="mt-9 flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-full bg-primary text-xs font-bold text-primary-foreground">SC</div><div><p className="text-sm font-semibold text-primary">Sofia Chen</p><p className="text-xs text-muted-foreground">CEO, Northline Studio</p></div></div></div></div></section>
    <section className="mx-auto flex max-w-[1320px] flex-col gap-8 px-5 py-24 sm:px-8 lg:flex-row lg:items-end lg:justify-between lg:px-12"><div><SectionLabel>Could be you</SectionLabel><h2 className="mt-5 max-w-2xl font-display text-5xl leading-[.98] text-primary sm:text-7xl">Bring us the bit you keep moving to next week.</h2></div><ArrowLink href="/contact">Let’s talk</ArrowLink></section>
  </div>;
}